name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests
    # TODO: Add flake8 and mypy back
    # - name: Run linter
    #   run: flake8 everything user_data device_data scripts tests
    # - name: Run type checker
    #   run: mypy everything user_data device_data scripts tests

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t everything-app .
    - name: Run Docker container
      run: docker run -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} everything-app python scripts/run_simulation.py